#=============================================#
#       Upper level makefile for Ingrid       #
#=============================================#

all:
	cd Efit; make; cd -
	cd Uegrid; make; cd -

clean:
	rm -f *.so *.pyc *.rst~ *.nml~
	rm -rf __pycache__/

