name: ingrid
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - fastcache=1.1.0
  - gmp=6.1.2
  - gmpy2=2.0.8
  - intel-openmp=2019.4
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - macholib=1.11
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0
  - numpy=1.17.2
  - numpy-base=1.17.2
  - openssl=1.0.2t
  - pip=19.2.3
  - pycrypto=2.6.1
  - pyinstaller=3.5
  - python=3.7.0
  - pyyaml=5.1.2
  - readline=7.0
  - scipy=1.3.1
  - setuptools=41.4.0
  - six=1.12.0
  - sqlite=3.30.0
  - sympy=1.4
  - tk=8.6.8
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - altgraph==0.16.1
    - cycler==0.10.0
    - kiwisolver==1.1.0
    - matplotlib==3.0.3
    - pyparsing==2.4.2
    - python-dateutil==2.8.0
