dir_settings:
  eqdsk: ''
  limiter: ''
  patch_data: ''
  target_plates: ''
eqdsk: ''
grid_settings:
  grid_generation:
    np_default: 2
    nr_default: 2
    poloidal_f_default: x, x
    radial_f_default: x, x
    skewness_correction:
      all:
        active: false
        resolution: 1000
        theta_max: 120.0
        theta_min: 80.0
  guard_cell_eps: 0.001
  nlevs: 30
  num_xpt: 1
  patch_generation:
    core_split_point_ratio: 0.5
    magx_tilt_1: 0.0
    magx_tilt_2: 0.0
    pf_split_point_ratio: 0.5
    rmagx_shift: 0.0
    strike_pt_loc: limiter
    use_xpt1_E: false
    use_xpt1_W: false
    use_xpt2_E: false
    use_xpt2_W: false
    xpt1_E_tilt: 0.785398
    xpt1_W_tilt: -0.785398
    xpt2_E_tilt: 0.785398
    xpt2_W_tilt: -0.785398
    zmagx_shift: 0.0
  psi_1: 0.0
  psi_2: 0.0
  psi_core: 0.0
  psi_pf_1: 0.0
  psi_pf_2: 0.0
  rmagx: 0.0
  rxpt: 0.0
  rxpt2: 0.0
  view_mode: filled
  zmagx: 0.0
  zxpt: 0.0
  zxpt2: 0.0
integrator_settings:
  dt: 0.01
  eps: 5.0e-05
  first_step: 1.0e-05
  max_step: 0.064
  step_ratio: 0.02
  tol: 0.005
limiter:
  efit_buffer_r: 0.01
  efit_buffer_z: 0.01
  file: ''
  rshift: 0.0
  use_efit_bounds: false
  zshift: 0.0
patch_data:
  file: ''
  preferences:
    new_file: false
    new_fname:  
  use_file: false
target_plates:
  plate_E1:
    file: ''
    rshift: 0.0
    zshift: 0.0
  plate_E2:
    file: ''
    rshift: 0.0
    zshift: 0.0
  plate_W1:
    file: ''
    rshift: 0.0
    zshift: 0.0
  plate_W2:
    file: ''
    rshift: 0.0
    zshift: 0.0
