#=============================================#
#       Upper level makefile for Ingrid       #
#=============================================#

all:
	cd Efit; make; cd -
	cd Interpol; make; cd -

clean:
	cd Efit; make clean; cd -
	cd Interpol; make clean; cd -
	rm -f *.so *.pyc