#=============================================#
#       Upper level makefile for Ingrid       #
#=============================================#

all:
	cd Efit; make; cd -

clean:
	cd Efit; make clean; cd -
	rm -f *.so *.pyc *.rst~ *.nml~\

